services:
  - type: web
    name: ai-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000

  - type: web
    name: ai-chatbot-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_frontend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 3000 